const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const chapters=$$('.chapter'),songAudio=$('#songAudio'),letterAudio=$('#letterAudio'),creditsAudio=$('#creditsAudio');
let currentChapter='opening',songIndex=0,code='',frostShown=false;
$$('.film-empty img,#frostToast img').forEach(img=>{const hide=()=>{img.hidden=true;img.parentElement?.classList.add('placeholder')};img.addEventListener('error',hide,{once:true});if(img.complete&&!img.naturalWidth)hide()});
const songs=[
 {title:'The Way I Loved You (Taylor’s Version)',artist:'Taylor Swift',file:"Taylor Swift - The Way I Loved You (Taylor's Version) (Lyric Video).mp3",photo:'DA586063-BF52-47A7-815E-258CB70CE27B.JPG',mood:'antique gold · the first song'},
 {title:'OK Jaanu — Title Track',artist:'A. R. Rahman',file:'OK Jaanu - Title Track  OK Jaanu  Shraddha Kapoor  Aditya Roy Kapoor  A. R. Rahman - SonyMusicIndiaVEVO.mp3',photo:'6ADE5806-1993-47E2-ACE6-B3E437F0723C.JPG',mood:'burgundy · jaanus & candlelight'},
 {title:'American Wedding (Hotel California)',artist:'dopuu',file:'american wedding (Hotel California) - dopuu.mp3',photo:'093295E0-BBF6-491E-932E-D5207CBC9B6C.JPG',mood:'charcoal · gold · after hours'},
 {title:'Othaiyadi Pathayila',artist:'Dhibu Ninan Thomas',file:'Kanaa - Othaiyadi Pathayila Video  Arunraja Kamaraj  Dhibu Ninan Thomas - SonyMusicSouthVEVO.mp3',photo:'288797B1-8B46-4706-ACBA-34BA5FFB424B.JPG',mood:'earth paper · kanmani'},
 {title:'Janam Janam',artist:'Pritam',file:'Janam Janam – Dilwale  Shah Rukh Khan  Kajol  Pritam  SRK  Kajol  Lyric Video 2015 - Sony Music India.mp3',photo:'191A5BDD-44F9-4353-8F32-14E309B0C53A.JPG',mood:'dark red · old favourite'},
 {title:'Love, Maybe (Acoustic Ver.)',artist:'Kim Se Jeong',file:'[Easy Lyrics] Kim Se Jeong - Love, Maybe (Acoustic Ver.) (A Business Proposal OST Bonus Track) - KR Drama OST.mp3',photo:'483D55F8-9D9E-412A-A3FC-7F0F1C110B33.JPG',mood:'sage green · a soft scene'},
 {title:'Good Luck Charm',artist:'K.S. Makhan',file:'Good Luck Charm - K.S. Makhan.mp3',photo:'F2DA05AD-8FDA-461A-BAF8-71F6566C7EDF.JPG',mood:'dusty pink · my good luck charm'}
];
const fileUrl=(p)=>p.split('/').map(encodeURIComponent).join('/');
function setChapter(id){if(!$('#'+id))return;const previous=currentChapter;chapters.forEach(c=>c.classList.toggle('active',c.id===id));currentChapter=id;window.scrollTo(0,0);
 if(previous==='music'){songAudio.pause();songAudio.currentTime=0;renderPlay(false)}
 if(previous==='letter'){letterAudio.pause();letterAudio.currentTime=0;renderLetterPlay(false)}
 if(previous==='credits'){creditsAudio.pause();creditsAudio.currentTime=0}
 if(id==='music'&&previous!=='music')renderSong();
 if(id==='record')tick(520,.035,.018,'sine');if(id==='booth')tick(930,.055,.018,'triangle');if(id==='bouquet')tick(420,.08,.018,'sine');
 if(id==='credits'){restartCredits();creditsAudio.currentTime=0;creditsAudio.play().catch(()=>{})}
 if(previous!=='opening'&&id!=='opening')maybeFrost();
}
$$('[data-next],[data-back]').forEach(b=>b.addEventListener('click',()=>setChapter(b.dataset.next||b.dataset.back)));
function maybeFrost(){if(frostShown||Math.random()>.32)return;frostShown=true;const toast=$('#frostToast');toast.classList.add('visible');playMeow();setTimeout(()=>toast.classList.remove('visible'),3900)}
function playMeow(){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.type='triangle';o.frequency.setValueAtTime(720,t);o.frequency.exponentialRampToValueAtTime(420,t+.22);o.frequency.exponentialRampToValueAtTime(560,t+.34);o.frequency.exponentialRampToValueAtTime(330,t+.56);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.035,t+.05);g.gain.exponentialRampToValueAtTime(.0001,t+.58);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+.6)}catch{}}
// Opening cake rises to reveal the next page.
$('#cakeTrigger').addEventListener('click',()=>{if($('#opening').classList.contains('lifting'))return;tick(440,.06,.022,'sine');$('#opening').classList.add('lifting');setTimeout(()=>setChapter('code'),850)});
// Small synthesized paper/lock clicks; no external sound files are needed.
let audioCtx;function tick(freq=650,duration=.045,gain=.035,type='sine'){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
const keys=['1','2','3','4','5','6','7','8','9','⌫','0','↵'];const keypad=$('#keypad');keys.forEach(k=>{const b=document.createElement('button');b.type='button';b.dataset.key=k;b.textContent=k;b.setAttribute('aria-label',k==='⌫'?'Delete':k==='↵'?'Enter':k);keypad.appendChild(b);b.addEventListener('click',()=>pressKey(k))});
function paintDots(){$$('#dots i').forEach((d,i)=>d.classList.toggle('filled',i<code.length))}
function submitCode(){if(code==='0210'){tick(260,.17,.055,'triangle');setTimeout(()=>tick(175,.24,.04,'sine'),110);keypad.classList.add('unlocked');setTimeout(()=>setChapter('music'),520)}else if(code.length){tick(145,.13,.035,'triangle');$('#codeMsg').textContent='';keypad.classList.remove('shake');void keypad.offsetWidth;keypad.classList.add('shake');code='';paintDots()}}
function pressKey(k){tick(k==='↵'?340:600,.035,.025);if(k==='⌫')code=code.slice(0,-1);else if(k==='↵')submitCode();else if(code.length<4){code+=k;if(code.length===4)setTimeout(submitCode,170)}paintDots()}
document.addEventListener('keydown',e=>{if(currentChapter!=='code')return;if(/^\d$/.test(e.key)&&code.length<4){code+=e.key;tick();paintDots();if(code.length===4)setTimeout(submitCode,170)}else if(e.key==='Backspace'){code=code.slice(0,-1);paintDots()}else if(e.key==='Enter')submitCode()});
// Record Club lists the same seven songs followed by the three locked tracks.
const recordTracks=[...songs.map(s=>({title:s.title,artist:s.artist,locked:false})),{title:'Harvey',artist:'Her’s',locked:true},{title:'Vaalam Aavo Ne',artist:'Sachin-Jigar',locked:true},{title:'Apocalypse',artist:'Cigarettes After Sex',locked:true}];
$('#tracks').innerHTML=recordTracks.map((t,i)=>`<div class="track ${t.locked?'is-locked':''}" ${t.locked?'':'role="button" tabindex="0"'}><span class="num">${String(i+1).padStart(2,'0')}</span><div><b>${t.title}</b><small>${t.artist}</small></div><span class="track-state" aria-label="${t.locked?'Locked':'In songbook'}">${t.locked?'\u2311':'\u266a'}</span></div>`).join('');
$('#spotifyBtn').href='https://open.spotify.com/playlist/7apVgBVFrDhUsOi96ANY9h?si=b5d78c7896d5424e&pt=59c6adea1cbaa1790d9e50d3c5910279';
$$('.track[role="button"]').forEach((row,index)=>{const play=()=>{songIndex=index;setChapter('music');$('#playBtn').click()};row.addEventListener('click',play);row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();play()}})});
function renderPlay(on){$('#playBtn').textContent=on?'Ⅱ':'▶';$('#playBtn').setAttribute('aria-label',on?'Pause':'Play')}
function renderSong(){const s=songs[songIndex];$('#musicCount').textContent=`${String(songIndex+1).padStart(2,'0')} / 07`;$('#songMood').textContent=s.mood;$('#songTitle').textContent=s.title;$('#songArtist').textContent=s.artist;$('#songPhoto').src=fileUrl(`assets/photos/${s.photo}`);$('#songPhoto').alt=`Rudri — ${s.title}`;$('#music').className=`chapter music world-${songIndex}`;if(currentChapter==='music')$('#music').classList.add('active');$('.film-mark b')?.replaceChildren(document.createTextNode(String(songIndex+1).padStart(2,'0')));songAudio.pause();songAudio.removeAttribute('src');songAudio.load();delete songAudio.dataset.track;$('#currentTime').textContent='0:00';$('#duration').textContent='—:—';$('#progress').value=0;$('#progress').style.setProperty('--played','0%');renderPlay(false);$('#musicNote').textContent=''}
function format(t){return Number.isFinite(t)?`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`:'0:00'}
function seekBy(n){if(Number.isFinite(songAudio.duration))songAudio.currentTime=Math.max(0,Math.min(songAudio.duration,songAudio.currentTime+n))}
$('#prevSong').addEventListener('click',()=>{songIndex=(songIndex+6)%7;renderSong()});$('#nextSong').addEventListener('click',()=>{songIndex=(songIndex+1)%7;renderSong()});
$('#playBtn').addEventListener('click',async()=>{if(songAudio.getAttribute('data-track')!==String(songIndex)){songAudio.pause();songAudio.src=fileUrl(`assets/audio/${songs[songIndex].file}`);songAudio.dataset.track=String(songIndex);songAudio.load()}if(songAudio.paused){try{await songAudio.play();renderPlay(true);$('#musicNote').textContent=''}catch{$('#musicNote').textContent='This audio file could not be played in this browser.'}}else{songAudio.pause();renderPlay(false)}});
$('#rewindBtn').addEventListener('click',()=>seekBy(-10));$('#forwardBtn').addEventListener('click',()=>seekBy(10));$('#progress').addEventListener('input',e=>{if(Number.isFinite(songAudio.duration)){songAudio.currentTime=songAudio.duration*e.target.value/100;e.target.style.setProperty('--played',`${e.target.value}%`)}});
songAudio.addEventListener('timeupdate',()=>{if(!Number.isFinite(songAudio.duration))return;$('#currentTime').textContent=format(songAudio.currentTime);$('#duration').textContent=format(songAudio.duration);const p=songAudio.currentTime/songAudio.duration*100;$('#progress').value=p;$('#progress').style.setProperty('--played',`${p}%`)});songAudio.addEventListener('ended',()=>renderPlay(false));
// Six 2D, rough notebook doodles and the requested captions.
const memories=[
 ['MEMORY 01','Two watches.','She wore two watches on different hands and told her dad that meant she had extra time in the world.','307ff075-b4d4-4258-86a9-8cab3170ed20.png'],
 ['MEMORY 02','Ice cream.','Ice cream hi hai meri sukh dukh ki saathi.','6858a76c-1628-446e-b6ac-cf3d6f7afcf1.png'],
 ['MEMORY 03','Little Ludrii.','Ludrii mera haath pakadd lo','bc58d197-4c86-4848-b1cf-c647254c271e.png'],
 ['MEMORY 04','Laboons.','mei bachpan me inhe laboons bulati thi','c1e3aa37-dced-4874-91f4-fb55807f9e7d.png'],
 ['MEMORY 05','Our future dream.','our future dream \u2728','c4090f87-a579-489f-ba07-2df71535dc36.png'],
 ['MEMORY 06','Kitchen team.','I cook while you keep us organized and hug me from behind. Your happy smile makes the whole kitchen feel like ours.','222336ba-c4f7-4120-816a-c5ecc373a8e0.png']
];
function drawMemory(i){const m=memories[i],art=$('#memoryArt');art.innerHTML=`<img loading="lazy" decoding="async" src="${fileUrl(`assets/memories/${m[3]}`)}" alt="${m[1]} hand-drawn memory">`}
$$('.flower-pin').forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.memory,m=memories[i];$('#memoryNo').textContent=m[0];$('#memoryTitle').textContent=m[1];$('#memoryText').textContent=m[2];drawMemory(i);$('#memoryModal').classList.add('show')}));
function closeMemory(){$('#memoryModal').classList.remove('show')}$('#closeMemory').addEventListener('click',closeMemory);$('#memoryModal').addEventListener('click',e=>{if(e.target===$('#memoryModal'))closeMemory()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMemory();if($('#letter').classList.contains('open'))setChapter('bouquet')}});
// The arithmetic surprise is tucked inside the bouquet page.
$('#mathStamp').addEventListener('click',()=>{if($('.quiz-paper'))return;const box=document.createElement('div');box.className='quiz-paper';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.innerHTML='<button class="quiz-close" aria-label="Close">×</button><span class="eyebrow">A LITTLE SIDE QUEST</span><h3>What is the square root of 20449?</h3><p>“I say this a lot to you.”</p><div class="quiz-options"><button>A. 0</button><button>B. 69</button><button>C. 143</button><button>D. scary calculus expression</button></div><small class="quiz-feedback" aria-live="polite"></small>';document.body.appendChild(box);box.querySelector('.quiz-close').onclick=()=>box.remove();box.querySelectorAll('.quiz-options button').forEach((b,i)=>b.onclick=()=>{box.querySelector('.quiz-feedback').textContent=i===2?'✦':'Try another one…';if(i===2)setTimeout(()=>box.remove(),1050)})});
function renderLetterPlay(on){$('#letterPlay').textContent=on?'PAUSE':'PLAY';$('#letterPlay').setAttribute('aria-label',on?'Pause Enchanted':'Play Enchanted')}
$('#letterVolume').addEventListener('input',e=>{letterAudio.volume=Number(e.target.value)});letterAudio.volume=.7;
function openLetter(){if($('#letter').classList.contains('open'))return;tick(205,.16,.04,'triangle');$('#letter').classList.add('open');$('#letterAudioController').hidden=false;letterAudio.play().then(()=>renderLetterPlay(true)).catch(()=>{})}
$('#seal').addEventListener('click',openLetter);$('#letterPlay').addEventListener('click',async()=>{if(letterAudio.paused){try{await letterAudio.play();renderLetterPlay(true)}catch{}}else{letterAudio.pause();renderLetterPlay(false)}});letterAudio.addEventListener('ended',()=>renderLetterPlay(false));
function restartCredits(){const roll=$('.credits-roll');roll.style.animation='none';void roll.offsetWidth;roll.style.animation=''}$('#skipCredits').addEventListener('click',()=>setChapter('finale'));$('.credits-roll').addEventListener('animationend',e=>{if(e.animationName==='roll')setChapter('finale')});
function openBoothPhoto(image,index){$('#lightboxImage').src=image.src;$('#lightboxImage').alt=image.alt;$('#lightboxCaption').textContent=`PHOTO ${String(index+1).padStart(2,'0')} / 05`;$('#boothLightbox').showModal()}
$$('.film-empty').forEach((frame,index)=>{const image=$('img',frame);frame.addEventListener('click',()=>openBoothPhoto(image,index));frame.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openBoothPhoto(image,index)}})});$('#closeLightbox').addEventListener('click',()=>$('#boothLightbox').close());$('#boothLightbox').addEventListener('click',e=>{if(e.target===$('#boothLightbox'))$('#boothLightbox').close()});
$('#restart').addEventListener('click',()=>{code='';paintDots();songIndex=0;songAudio.pause();letterAudio.pause();creditsAudio.pause();$('#letterAudioController').hidden=true;$('#keypad').classList.remove('unlocked');$('#opening').classList.remove('lifting');$('#letter').classList.remove('open');frostShown=false;setChapter('opening')});
// Static build: populate an audio smoke-check list for browser devtools / QA.
window.birthdayExperience={songs:songs.map(s=>({...s,url:fileUrl(`assets/audio/${s.file}`)})),chapters:chapters.map(c=>c.id)};
renderSong();
