const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const chapters = $$('.chapter');
function go(id){ chapters.forEach(c=>c.classList.toggle('active',c.id===id)); localStorage.setItem('rudriChapter',id); window.scrollTo({top:0,behavior:'smooth'}); }
$$('[data-next]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.next)));

// OPENING: physical foil/parchment reveal
let taps=0;
const foil=$('#foilPaper');
foil.addEventListener('click',()=>{
  taps++;
  foil.classList.remove('tap1','tap2','tap3');
  foil.classList.add('tap'+Math.min(taps,3));
  if(taps===1) $('#tapNote').textContent='again…';
  if(taps===2) $('#tapNote').textContent='one more…';
  if(taps>=3){
    $('#opening').classList.add('revealed');
    $('#tapNote').textContent='';
    setTimeout(()=>$('#birthdayReveal').classList.add('show'),350);
  }
});

// CODE KEYPAD — generated by JS, so it works as real buttons
const keys=['1','2','3','4','5','6','7','8','9','⌫','0','↵'];
const keypad=$('#keypad');
keys.forEach(k=>{const b=document.createElement('button');b.type='button';b.dataset.key=k;b.textContent=k;keypad.appendChild(b);});
let code='';
function paintDots(){ $$('#dots i').forEach((d,i)=>d.classList.toggle('filled',i<code.length)); }
keypad.addEventListener('click',e=>{
  const b=e.target.closest('button'); if(!b)return;
  const k=b.dataset.key;
  if(k==='⌫') code=code.slice(0,-1);
  else if(k==='↵'){
    if(code==='0210'){
      $('#codeMsg').textContent='unlocked ♥';
      setTimeout(()=>go('record'),450);
    }else{
      $('#codeMsg').textContent='not quite… try again.';
      keypad.classList.remove('shake'); void keypad.offsetWidth; keypad.classList.add('shake');
      code='';
    }
  }else if(code.length<4) code+=k;
  paintDots();
});

// RECORD CLUB
const trackData=[
 ['01','Sweet Disposition','The Temper Trap'],['02','Every Summertime','NIKI'],['03','Glue Song','beabadoobee'],
 ['04','Until I Found You','Stephen Sanchez'],['05','Lover Boy','Phum Viphurit'],['06','Ribs','Lorde'],
 ['07','Dreams','The Cranberries'],['08','Sunflower','Rex Orange County'],['09','the one that is SO you','???']
];
const tracks=$('#tracks');
tracks.innerHTML=trackData.map(t=>`<div class="track"><span class="num">${t[0]}</span><div class="track-info"><b>${t[1]}</b><small>${t[2]}</small></div><button class="playdot" type="button" aria-label="Play ${t[1]}">▶</button></div>`).join('');
$$('.playdot').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation(); b.textContent=b.textContent==='▶'?'Ⅱ':'▶';}));
$('#spotifyBtn').addEventListener('click',()=>alert('Add your real Spotify playlist URL here when you are ready ♥'));

// MUSIC EXPERIENCE
const songs=[
 ['dreamy','Song One','Artist One','#a95374'],['velvet','Song Two','Artist Two','#70263f'],['midnight','Song Three','Artist Three','#314968'],
 ['sunlit','Song Four','Artist Four','#a8734d'],['cloudy','Song Five','Artist Five','#696486'],['royal','Song Six','Artist Six','#7c2940'],['soft','Song Seven','Artist Seven','#98716c']
];
let si=0, playing=false;
function renderSong(){const s=songs[si];$('#musicCount').textContent=`0${si+1} / 07`;$('#songMood').textContent=s[0];$('#songTitle').textContent=s[1];$('#songArtist').textContent=s[2];$('#musicBg').style.background=`radial-gradient(circle at 50% 22%,${s[3]} 0%, #351522 42%, #10080d 100%)`;$('#progress').style.width=`${18+si*10}%`;$('#playBtn').textContent='▶';playing=false;}
renderSong();
$('#prevSong').addEventListener('click',()=>{si=(si+6)%7;renderSong();});
$('#nextSong').addEventListener('click',()=>{si=(si+1)%7;renderSong();});
$('#playBtn').addEventListener('click',()=>{playing=!playing;$('#playBtn').textContent=playing?'Ⅱ':'▶';});

// BOUQUET
const memories=[
 ['memory 01','Two watches.','She wore two watches, one on each hand, and decided this meant she had more time than everyone else.'],
 ['memory 02','The ceiling monsters.','There was a time when the shower was absolutely not happening unless Mum came to investigate the ceiling first.'],
 ['memory 03','Tiny chaos.','One of those childhood stories that somehow gets funnier every time it is retold.'],
 ['memory 04','The dramatic era.','A tiny person with enormous opinions. Honestly, not much has changed.'],
 ['memory 05','Little collector.','Another tiny detail from the archive of things that make Rudri, Rudri.'],
 ['memory 06','Main character.','A memory that deserves its own little frame in this ridiculous museum.'],
 ['memory 07','To be continued.','Some stories are still being written.']
];
$$('.flower').forEach(f=>f.addEventListener('click',()=>{const m=memories[+f.dataset.memory];$('#memoryNo').textContent=m[0];$('#memoryTitle').textContent=m[1];$('#memoryText').textContent=m[2];$('#memoryModal').classList.add('show');}));
$('#closeMemory').addEventListener('click',()=>$('#memoryModal').classList.remove('show'));

// LETTER
$('#seal').addEventListener('click',()=>$('#letter').classList.add('open'));

// Safe resume: never blocks the page with confirm on load.
const saved=localStorage.getItem('rudriChapter');
if(saved && saved!=='opening'){
  const resume=$('#resumeToast');
  if(resume){resume.hidden=false; $('#resumeYes').onclick=()=>{resume.hidden=true;go(saved)};$('#resumeNo').onclick=()=>{resume.hidden=true;go('opening');localStorage.removeItem('rudriChapter');};}
  else go('opening');
}else go('opening');
